name: Run Bot Application

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Use an Ubuntu virtual machine

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  
        
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the bot using secrets for API keys
    - name: Run Bot
      env:
        ASSEMBLYAI_KEY: ${{ secrets.ASSEMBLYAI_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
      run: |
        python bot.py
